### ISSUE TITLE
List Property Bookings - Search issues

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#362]
9.16.1
No overrides in core and using JR_Leohtian_WP 2.1.0 without override html

Booking data set
3 bookings for same last name(taylor) & email address (allytaylor@xyz.com)
4 cancelled bookings with 1 having same email (allytaylor@xyz.com) and 3 others with a different email but also having taylor in the address. 

All 7 bookings having taylor as lastname

Booking number | First name | Last name | Email
-- | -- | -- | --
71346648 | test4a | taylor | allytaylor@xyz.com
94361300 | test4a | taylor | allytaylor@xyz.com
37368869 | test4 | taylor | allytaylor@xyz.com
56551469 |   |   |  
70022073 |   |   |  
78353721 |   |   |  
34097400 |   |   |  
______________________________________

When using search for last name the result is

Booking number | First name | Last name | Email
-- | -- | -- | --
37368869 | test4 | taylor | allytaylor@xyz.com
78353721 |   |   |  
34097400 |   |   |  

________________________________________

When using search for email, the result is

Booking number | First name | Last name | Email
-- | -- | -- | --
37368869 | test4 | taylor | allytaylor@xyz.com
34097400 |   |   |  

Issue is that search results are incomplete for either email or last name.

This functionality was consistently possible & reliably accurate in previous versions.

**Comment by jomres** [comment]
For the record, I've played around with several possibilities but so far have no solution readily available. 

The problem is caused by the encryption process. If you were to search on the date, that would work because the dates of the bookings aren't encrypted. If you want to search however on the guest name, that's more problematic because you can't simply encrypt "bob" and seasch on that instead. 

Right now, the only solution I can think of is to pull all guest names/addresses/phone numbers/email addresses , decrypt them, see which match the query and then in what is the current query search only those guest uids. That would add to the processing time, so I'm going to think on this more before attempting that.

**Comment by jomres** [comment]
Ally, can you update the nightly and confirm that the changed added last night resolves the problem?

**Comment by allynat** [comment]
Hi Vince
I believe I have been previously confused when I agreed this is sorted.

I have 9.17 installed and the search of first or last name does not work.

If I remove the following change, then the search does work.

/* 		if (isset($search['value']) && $search['value'] != '') {
			$sWhere = 'AND (';
			for ($i = 0; $i < $n; ++$i) {
				$sWhere .= ''.$aColumns[$i]." LIKE '%".$search['value']."%' OR ";
			}
			$sWhere = rtrim($sWhere, ' OR ');
			$sWhere .= ')';
			
		} */
		
		$guest_matches = search_property_guests_by_string( $search['value'] , $defaultProperty , $thisJRUser->id , $show_all );
		if ( isset($guest_matches['guest_uids']) && !empty($guest_matches['guest_uids'])) {
			$sWhere = 'AND (';
			$count = count($guest_matches['guest_uids']);
			for ($i = 0; $i < $count; ++$i) {
				$sWhere .= "b.guests_uid = '".$guest_matches['guest_uids'][$i]."' OR ";
			}
			$sWhere = rtrim($sWhere, ' OR ');
			$sWhere .= ')';
		}

		/*

Sorry!

**Comment by allynat** [comment]
And further :(

If a booking is made with a ZERO value tariff - because it is free, then List Bookings does not show the  booking.

Room bookings, contracts and invoices are created but the bookings are missing from display.

Regards

Ally

**Comment by jomres** [comment]
> 
> 
> Hi Vince
> I believe I have been previously confused when I agreed this is sorted.
> 

Nope. There's a new change I added last night that should resolve this. You weren't confused, but like me you tested the part that concerned you and not the rest. The change added last night affects the rest.

**Comment by allynat** [comment]
Hi Vince

I have updated using the overnight, removed any custom_code affecting List Bookings and note that I can search on a last name & a booking number.

Is that correct?

"The change added last night affects the rest.”

Can you please point me at what “the rest” is because with zero contract_total in a contract the record is still not displayed.

Thanks Vince

Ally
